### ISSUE TITLE
Warning in logs

### ISSUE THREAD

**Issue by bru73f0rc3** [rt400/Jewish-Sabbaths-Holidays#24]
Shortly after startup i get the following:
```
WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'hebcal' at custom_components/hebcal/sensor.py, line 516: return utc_dt.replace(tzinfo=datetime.timezone.utc).astimezone(tz=pytz.timezone(timezone)) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/rt400/Jewish-Sabbaths-Holidays/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/hebcal/sensor.py", line 228, in async_update
    await self.create_db_file()
  File "/config/custom_components/hebcal/sensor.py", line 286, in create_db_file
    await self.filter_db(temp_db["items"], "new")
  File "/config/custom_components/hebcal/sensor.py", line 360, in filter_db
    extract_data["start"] = self.sunset_time(extract_data["date"], -1)
  File "/config/custom_components/hebcal/sensor.py", line 488, in sunset_time
    sunset = self.utc_to_local(data, str(self._timezone))
  File "/config/custom_components/hebcal/sensor.py", line 516, in utc_to_local
    return utc_dt.replace(tzinfo=datetime.timezone.utc).astimezone(tz=pytz.timezone(timezone))
```

Everything seems to be working fine except for the warning.
installed via hacs, running latest, and latest hassOS with latest hass core.

**Comment by rt400** [comment]
try to restart your HA and see i the warning came again.
on my HA i didn't see it

**Comment by rt400** [comment]
> Yes, I see it after restart and after upgrade. Started off with a clean install of hassOS 2024.9, upgraded to 2024.10 and 2024.10.1. It's a pretty clean setup for now. Let me know if there's any data I can grab for you beyond the log.

which country you use? or timezone ?

**Comment by rt400** [comment]
@bru73f0rc3 if you have access to sensor.py then try to copy and paste from this link : https://paste.ofcode.org/pyFHRL5ELRq4X54RJhvgYK
and make restart to HA and let me know if the warning still appear..

**Comment by rt400** [comment]
Good to know...
i will upload this fix to the git later.
let me know if the error will popup again.
